### ISSUE TITLE
`dvc push` fails with "Timeout on reading data from socket" with HTTP storage

### ISSUE THREAD

**Issue by sisp** [iterative/dvc-http#27]
# Bug Report

## Description

When trying to push some moderately large amount of data (e.g. 1 GB) to a [GitLab generic packages repository](https://docs.gitlab.com/ee/user/packages/generic_packages/) (via the HTTP remote storage type), the upload fails after a few (e.g. 5) minutes with the following  timeout error:

```shell-session
$ dvc push -v
2022-07-28 17:33:07,919 DEBUG: Preparing to transfer data from '/home/user/dev/dvc-test/.dvc/cache' to 'https://gitlab.com/api/v4/projects/<project_id>/packages/generic/dvc-data'
2022-07-28 17:33:07,919 DEBUG: Preparing to collect status from 'https://gitlab.com/api/v4/projects/<project_id>/packages/generic/dvc-data'
2022-07-28 17:33:07,919 DEBUG: Collecting status from 'https://gitlab.com/api/v4/projects/<project_id>/packages/generic/dvc-data'
2022-07-28 17:33:07,920 DEBUG: Querying 2 hashes via object_exists                                                                                                                                         
2022-07-28 17:33:08,249 DEBUG: Preparing to collect status from '/home/user/dev/dvc-test/.dvc/cache'                                                                
2022-07-28 17:33:08,250 DEBUG: Collecting status from '/home/user/dev/dvc-test/.dvc/cache'
2022-07-28 17:33:08,331 DEBUG: Uploading '/home/user/dev/dvc-test/.dvc/cache/1c/90d4b78d043e2a58e0746231c9024f' to 'https://gitlab.com/api/v4/projects/<project_id>/packages/generic/dvc-data/1c/90d4b78d043e2a58e0746231c9024f'
2022-07-28 17:38:09,183 ERROR: failed to transfer 'md5: 1c90d4b78d043e2a58e0746231c9024f' - : Timeout on reading data from socket                                                                          
------------------------------------------------------------                                                                                                                                               
Traceback (most recent call last):
  File "<site-packages>/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "<site-packages>/fsspec/implementations/http.py", line 294, in _put_file
    async with meth(rpath, data=gen_chunks(), **kw) as resp:
  File "<site-packages>/aiohttp_retry/client.py", line 98, in __aenter__
    return await self._do_request()
  File "<site-packages>/aiohttp_retry/client.py", line 86, in _do_request
    raise e
  File "<site-packages>/aiohttp_retry/client.py", line 71, in _do_request
    response: ClientResponse = await self._request(
  File "<site-packages>/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "<site-packages>/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "<site-packages>/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerTimeoutError: Timeout on reading data from socket

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<site-packages>/dvc/data/transfer.py", line 25, in wrapper
    func(fs_path, *args, **kwargs)
  File "<site-packages>/dvc/data/transfer.py", line 162, in func
    return dest.add(
  File "<site-packages>/dvc/objects/db.py", line 126, in add
    self._add_file(
  File "<site-packages>/dvc/objects/db.py", line 98, in _add_file
    return fs.utils.transfer(
  File "<site-packages>/dvc/fs/utils.py", line 96, in transfer
    _try_links(links, from_fs, from_path, to_fs, to_path)
  File "<site-packages>/dvc/fs/utils.py", line 66, in _try_links
    return _copy(from_fs, from_path, to_fs, to_path)
  File "<site-packages>/dvc/fs/utils.py", line 44, in _copy
    return to_fs.upload(from_path, to_path)
  File "<site-packages>/dvc/fs/base.py", line 386, in upload
    return self.put_file(from_info, to_info, callback=cb, size=size)
  File "<site-packages>/dvc/fs/http.py", line 151, in put_file
    super().put_file(
  File "<site-packages>/dvc/fs/base.py", line 329, in put_file
    self.fs.put_file(
  File "<site-packages>/fsspec/asyn.py", line 85, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "<site-packages>/fsspec/asyn.py", line 63, in sync
    raise FSTimeoutError from return_result
fsspec.exceptions.FSTimeoutError
------------------------------------------------------------
2022-07-28 17:38:09,197 ERROR: failed to push data to the cloud - 1 files failed to upload                                                                                                                 
------------------------------------------------------------
Traceback (most recent call last):
  File "<site-packages>/dvc/repo/push.py", line 68, in push
    pushed += self.cloud.push(
  File "<site-packages>/dvc/data_cloud.py", line 85, in push
    return transfer(
  File "<site-packages>/dvc/data/transfer.py", line 176, in transfer
    _do_transfer(
  File "<site-packages>/dvc/data/transfer.py", line 116, in _do_transfer
    raise FileTransferError(total_fails)
dvc.exceptions.FileTransferError: 1 files failed to transfer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<site-packages>/dvc/commands/data_sync.py", line 58, in run
    processed_files_count = self.repo.push(
  File "<site-packages>/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "<site-packages>/dvc/repo/push.py", line 72, in push
    raise UploadError(exc.amount)
dvc.exceptions.UploadError: 1 files failed to upload
```

### Reproduce

1. Create a new project on gitlab.com and take a note of the project ID.
2. Create a deploy token under `Settings > Repository > Deploy tokens` with scope `write_package_registry`.
3. Clone the project from gitlab.com locally and change the current working directory to the cloned project.
4. Initialize DVC and configure the remote storage:
   ```sh
   dvc init
   dvc remote add -d gitlab https://gitlab.com/api/v4/projects/<project_id>/packages/generic/dvc-data
   dvc remote modify gitlab method PUT
   dvc remote modify gitlab auth custom
   dvc remote modify --local gitlab custom_auth_header 'DEPLOY-TOKEN'
   dvc remote modify --local gitlab password <deploy_token>
   ```
5. Create some data and and track it with DVC:
   ```sh
   mkdir data
   head -c 1G /dev/urandom > data/data.txt
   dvc add data/data.txt
   ```
6. Push the data to the DVC remote storage:
   ```sh
   dvc push -v
   ```

### Expected

Successful upload of the data.

When I upload the same data to the GitLab generic packages repository via cURL, it works fine:

```sh
curl \
  --header "DEPLOY-TOKEN: <deploy_token>" \
  --upload-file data/data.txt \
  https://gitlab.com/api/v4/projects/<project_id>/packages/generic/dvc-data/test/data.txt
```

### Environment information

**Output of `dvc doctor`:**

```shell-session
$ dvc doctor
DVC version: 2.10.2 (snap)
---------------------------------
Platform: Python 3.8.10 on Linux-5.13.0-48-generic-x86_64-with-glibc2.29
Supports:
	azure (adlfs = 2022.4.0, knack = 0.9.0, azure-identity = 1.10.0),
	gdrive (pydrive2 = 1.10.1),
	gs (gcsfs = 2022.3.0),
	webhdfs (fsspec = 2022.3.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.3.0, boto3 = 1.21.21),
	ssh (sshfs = 2022.3.1)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/vgubuntu-root
Caches: local
Remotes: https, https
Workspace directory: ext4 on /dev/mapper/vgubuntu-root
Repo: dvc, git
```

**Additional Information (if any):**

n/a

**Comment by dtrifiro** [comment]
Merged https://github.com/iterative/dvc/pull/8722.

`read_timeout` can be now set in the http remote config. Set to `0` to disable timeout. Please note that this *may* result in indeterminate hangs under certain network conditions.

Waiting for upstream in the meantime

**Comment by altosaar** [comment]
Also facing this issue! How can I set to `0` to disable the timeout @dtrifiro ? Thank you!!

**Comment by jinensetpal** [comment]
I'm guessing: `dvc config set core.read_timeout 0`

Can't test since I'm on my smartphone

**Comment by marcusos** [comment]
Hi folks! How can I set the read_timeout? I am trying to add a new config as suggested, but I got an error:

 `configuration error - config file error: extra keys not allowed @ data['remote']['origin']['timeout']`

**Comment by dtrifiro** [comment]
Hi @marcusos, it should be enough to set it using `dvc remote modify <remote name> read_timeout 0`.

Please make sure you're running `dvc>=2.39.0` and `dvc-http>=2.30.1`

**Comment by skshetry** [comment]
@marcusos, is it possible to use `pip`? We released a new version of `dvc-http` yesterday that should fix this, so homebrew will have to wait for the next release.

**Comment by marcusos** [comment]
Thank you @skshetry !

**Comment by skshetry** [comment]
Closed by https://github.com/aio-libs/aiohttp/pull/7150, thanks to @dtrifiro.

We are still waiting for a release though. Meanwhile, there are `connect_timeout`/`read_timeout` options that you can set.
